apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: std-jira
  namespace: prod-vsc
spec:
  tls:
    - hosts:
        - jira.inso.gov.ir
      secretName: std-jira-ingress-tls
  ingressClassName: nginx
  rules:
    - host: jira.inso.gov.ir
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: std-jira
                port:
                  name: http
